version: "3.7"
services:
  react:
    build:
      args:
        - NODE_VER=20.11.1
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      # - .:/home/node/app
      - ./frontend:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 5173:5173
volumes:
  node_modules: